### ISSUE TITLE
IGC build errors against LLVM-9

### ISSUE THREAD

**Issue by dvrogozh** [intel/intel-graphics-compiler#59] opened 2019-02-12 22:46 UTC
I was trying to build IGC against LLVM-9 following the instruction here: #54. There are few non-trivial incompatibilities which are beyond my knowledge of LLVM. For example:
```
/home/dvrogozh/git/github/tmp/igc/IGC/GenISAIntrinsics/GenIntrinsics.cpp:519:83: error: no matching function for call to ‘cast<llvm::Function>(llvm::FunctionCallee)’
/home/dvrogozh/git/github/tmp/igc/IGC/Compiler/CISACodeGen/ResolveGAS.cpp:595:14: error: cannot convert ‘llvm::FunctionCallee’ to ‘llvm::Constant*’ in assignment
```

I think that this incompatibility came after this LLVM change: https://github.com/llvm/llvm-project/commit/13680223b9d80bb01e17372f0907cf215e424cce.

Please, be aware of the problem. Can someone, please, guide on how to fix or help to fix? I will attach full log.

[llvm9_build_log.txt](https://github.com/intel/intel-graphics-compiler/files/2857998/llvm9_build_log.txt)

**UPDATE**

> I was able to resolve trivial issues just reusing LLVM-8 path, here is a patch for that: #58

These changes landed as https://github.com/intel/intel-graphics-compiler/commit/80db6d648656e89e1ca82f176c04fc77190a9410

**Comment by lwesiers** [comment] 2019-06-07 13:09
@dvrogozh : please check this doc : https://github.com/intel/intel-graphics-compiler/blob/master/documentation/build_ubuntu.md

Current sources of IGC are available to build with llvm9/clang9. Please close this topic if the issue is resolved. Feel free to reopen this issue, if you will notice a build break with the latest sources.

**Comment by dvrogozh** [comment] 2019-06-07 14:08
I will try out to build against llvm-9. Thank you for update.

BTW, the link in the primary README.md is wrong and does not work. It is set as https://github.com/intel/intel-graphics-compiler/master/documentation/build_ubuntu.md instead of working
https://github.com/intel/intel-graphics-compiler/blob/master/documentation/build_ubuntu.md

**Closed** 2019-06-24 15:49 UTC
