### ISSUE TITLE
RFE: please update igc for latest LLVM

### ISSUE THREAD

**Issue by kloczek** [intel/intel-graphics-compiler#339] opened 2024-08-15 13:36 UTC
Currently igc can be compiled only against ancient llvm 14.

Please start update for latest 18 or already branched 19.

**Comment by frantisekz** [comment] 2024-08-20 12:21
Fedora is shipping igc built against LLVM 15 which works just fine, and relevant discussion is at #289 for updates and progress.

**Comment by kloczek** [comment] 2024-08-20 12:23
Yes and it i ONLY package which still needs LLVM 15 binaries.

**Comment by pszymich** [comment] 2024-09-24 09:24
Closing as duplicate of #289. Please follow that issue for updates.

**Closed by pszymich** 2024-09-24 09:24 UTC
