### ISSUE TITLE
doesn't build with llvm 11

### ISSUE THREAD

**Issue by tjaalton** [intel/intel-graphics-compiler#154] opened 2020-11-12 11:34 UTC
/<<PKGBUILDDIR>>/IGC/Compiler/CustomSafeOptPass.cpp: In member function ‘void IGC::GenSpecificPattern::visitBinary
Operator(llvm::BinaryOperator&)’:
/<<PKGBUILDDIR>>/IGC/Compiler/CustomSafeOptPass.cpp:2323:74: error: ‘static llvm::VectorType* llvm::VectorType::ge
t(llvm::Type*, unsigned int)’ is deprecated [-Werror=deprecated-declarations]
 2323 |                 VectorType* vec4 = VectorType::get(builder.getInt8Ty(), 4);
      |                                                                          ^

this with 1.0.5353.1 on current Debian unstable

**Comment by ArchangeGabriel** [comment] 2020-11-14 22:14
Duplicate of #152, fixed in latest release (1.0.5435).

**Comment by lwesiers** [comment] 2020-11-16 10:19
Closing this issue, as it was fixed. Feel free to reopen if similar issue will arrive.

**Closed by lwesiers** 2020-11-16 10:19 UTC
