### ISSUE TITLE
clBuildProgram crash in the inliner

### ISSUE THREAD

**Issue by JacekDanecki** [intel/intel-graphics-compiler#127] opened 2020-03-23 07:31 UTC
Moving issue from Neo: https://github.com/intel/compute-runtime/issues/283, as crash is on IGC side.

**Comment by lwesiers** [comment] 2020-03-24 12:53
Hello there @pjaaskel

Could you please run reproduction with environment variable "IGC_ShaderDumpEnable=1" ?

After executing reproduction you should have in folder "/tmp/IntelIGC" shader dumps. Please send me them, so I can start debug.

Thanks!

**Comment by pjaaskel** [comment] 2020-03-24 14:03
Here you go:
[image-classifier.tar.gz](https://github.com/intel/intel-graphics-compiler/files/4375660/image-classifier.tar.gz)

**Comment by lwesiers** [comment] 2020-03-24 16:36
Thanks for the shader dumps! Indeed, we have a crash in this shader using [igc-1.0.3529](https://github.com/intel/intel-graphics-compiler/releases/tag/igc-1.0.3529). I noticed, that we committed already a [fix](https://github.com/intel/intel-graphics-compiler/commit/0b03710093d2211561d6025dea22a0972e07ea23) - and with this I was able to compile successfully this shader. Please rebuild&install IGC compiler using this [commit-hash](https://github.com/intel/intel-graphics-compiler/commit/0b03710093d2211561d6025dea22a0972e07ea23) to fix this crash. Feel free to re-open this issue - if the crash will be still present on your side.

**Closed by lwesiers** 2020-03-24 16:36 UTC

**Comment by pjaaskel** [comment] 2020-03-25 07:25
Thanks, I'll try building from the sources. The fix looks like a workaround though. Is it addressing the underlying issue? It increases the inline threshold so the inliner inlines more -- perhaps there's a case where the compiler is not prepared to see non-inlined function calls intact in this case? Anyhow -- if it works, it works :)
