### ISSUE TITLE
Prebuilt VC Intrinsics

### ISSUE THREAD

**Issue by Bidski** [intel/intel-graphics-compiler#142] opened 2020-08-03 04:36 UTC
Is it possible prebuild VC Intrinsics for the VectorCompiler module rather than needing to have the vc-intrisincs sources available?

**Comment by ArchangeGabriel** [comment] 2020-08-09 09:26
That would indeed be better for distro packaging.

**Comment by ArchangeGabriel** [comment] 2020-10-13 14:28
I’d like to refresh this question since we are going to upgrade our stack to LLVM 11 soon and resume IGC upgrade on Arch Linux. ;)

**Comment by eero-t** [comment] 2020-11-16 09:41
See also: https://github.com/intel/vc-intrinsics/issues/36

**Comment by tjaalton** [comment] 2021-11-17 09:25
I finally got intel-vc-intrinsics package accepted in Debian, and then I see this..

**Comment by eero-t** [comment] 2022-02-17 10:36
> I finally got intel-vc-intrinsics package accepted in Debian, and then I see this..

Based on there being no responses to this from IGC developers since it was opened 1.5 years ago, it does not seem like bundling is going to happen...

**Comment by eero-t** [comment] 2022-02-23 12:43
FYI: vc-intrinsics project has now its first tag (v0.1.0).

**Comment by pszymich** [comment] 2022-02-23 22:23
A commit adding support for prebuilt/preinstalled VC intrinsics package has been merged recently: https://github.com/intel/intel-graphics-compiler/commit/35c947c2631ef4948532eb65c4a62434a580dd3d
Thank you @StepanMishura!

Please verify if that solves the problem. Thanks!

**Comment by ArchangeGabriel** [comment] 2022-03-04 23:40
Works fine, thanks!

**Comment by ArchangeGabriel** [comment] 2022-03-04 23:57
Actually spoken too fast. While the prebuilt intrinsics gets properly detected, compilation fails with:
```
../../../../Release/libCMCLSupport.a(BuiltinTranslator.cpp.o): in function `llvm::Function* getGenXDeclarationForIdFromArgs<std::vector<llvm::Value*, std::allocator<llvm::Value*> > const&>(llvm::Type&, std::vector<llvm::Value*, std::allocator<llvm::Value*> > const&, llvm::GenXIntrinsic::ID, llvm::Module&)':
/build/intel-graphics-compiler/src/intel-graphics-compiler-igc-1.0.10409/IGC/VectorCompiler/CMCL/lib/Support/BuiltinTranslator.cpp:110: undefined reference to `llvm::GenXIntrinsic::isOverloadedRet(unsigned int)'
/usr/bin/ld: /build/intel-graphics-compiler/src/intel-graphics-compiler-igc-1.0.10409/IGC/VectorCompiler/CMCL/lib/Support/BuiltinTranslator.cpp:117: undefined reference to `llvm::GenXIntrinsic::isOverloadedArg(unsigned int, unsigned int)'
/usr/bin/ld: /build/intel-graphics-compiler/src/intel-graphics-compiler-igc-1.0.10409/IGC/VectorCompiler/CMCL/lib/Support/BuiltinTranslator.cpp:121: undefined reference to `llvm::GenXIntrinsic::getGenXDeclaration(llvm::Module*, llvm::GenXIntrinsic::ID, llvm::ArrayRef<llvm::Type*>)'
```
Switching back to sources works.

**Comment by ArchangeGabriel** [comment] 2022-03-17 21:42
Actually I’m facing similar errors with `ispc`, also building with those prebuilt vc-intrinsics:
```
/usr/bin/ld: /tmp/lto-llvm-d034b8.o: in function `ispc::AddBitcodeToModule(ispc::BitcodeLib const*, llvm::Module*, ispc::SymbolTable*)':
ld-temp.o:(.text._ZN4ispc18AddBitcodeToModuleEPKNS_10BitcodeLibEPN4llvm6ModuleEPNS_11SymbolTableE+0x20e): undefined reference to `llvm::GenXIntrinsic::getGenXIntrinsicID(llvm::Function const*)'
/usr/bin/ld: ld-temp.o:(.text._ZN4ispc18AddBitcodeToModuleEPKNS_10BitcodeLibEPN4llvm6ModuleEPNS_11SymbolTableE+0x219): undefined reference to `llvm::GenXIntrinsic::getAttributes(llvm::LLVMContext&, llvm::GenXIntrinsic::ID)'
/usr/bin/ld: /tmp/lto-llvm-d034b8.o: in function `ispc::FunctionEmitContext::BranchInst(llvm::BasicBlock*, llvm::BasicBlock*, llvm::Value*)':
ld-temp.o:(.text._ZN4ispc19FunctionEmitContext10BranchInstEPN4llvm10BasicBlockES3_PNS1_5ValueE+0x175): undefined reference to `llvm::GenXIntrinsic::getGenXDeclaration(llvm::Module*, llvm::GenXIntrinsic::ID, llvm::ArrayRef<llvm::Type*>)'
/usr/bin/ld: /tmp/lto-llvm-d034b8.o: in function `ispc::FunctionEmitContext::XeSimdCFPredicate(llvm::Value*, llvm::Value*)':
ld-temp.o:(.text._ZN4ispc19FunctionEmitContext17XeSimdCFPredicateEPN4llvm5ValueES3_+0x92): undefined reference to `llvm::GenXIntrinsic::getGenXDeclaration(llvm::Module*, llvm::GenXIntrinsic::ID, llvm::ArrayRef<llvm::Type*>)'
/usr/bin/ld: /tmp/lto-llvm-d034b8.o: in function `ispc::FunctionEmitContext::XeStartUnmaskedRegion()':
ld-temp.o:(.text._ZN4ispc19FunctionEmitContext21XeStartUnmaskedRegionEv+0x35): undefined reference to `llvm::GenXIntrinsic::getGenXDeclaration(llvm::Module*, llvm::GenXIntrinsic::ID, llvm::ArrayRef<llvm::Type*>)'
/usr/bin/ld: /tmp/lto-llvm-d034b8.o: in function `ispc::FunctionEmitContext::XeEndUnmaskedRegion(llvm::Value*)':
ld-temp.o:(.text._ZN4ispc19FunctionEmitContext19XeEndUnmaskedRegionEPN4llvm5ValueE+0x47): undefined reference to `llvm::GenXIntrinsic::getGenXDeclaration(llvm::Module*, llvm::GenXIntrinsic::ID, llvm::ArrayRef<llvm::Type*>)'
/usr/bin/ld: /tmp/lto-llvm-d034b8.o: in function `ispc::lIsSVMLoad(llvm::Instruction*)':
ld-temp.o:(.text._ZN4ispc10lIsSVMLoadEPN4llvm11InstructionE+0x20): undefined reference to `llvm::GenXIntrinsic::getGenXIntrinsicID(llvm::Function const*)'
/usr/bin/ld: /tmp/lto-llvm-d034b8.o: in function `ispc::Module::AddLLVMIntrinsicDecl(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ispc::ExprList*, ispc::SourcePos)':
ld-temp.o:(.text._ZN4ispc6Module20AddLLVMIntrinsicDeclERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNS_8ExprListENS_9SourcePosE+0x66): undefined reference to `llvm::GenXIntrinsic::lookupGenXIntrinsicID(llvm::StringRef)'
/usr/bin/ld: ld-temp.o:(.text._ZN4ispc6Module20AddLLVMIntrinsicDeclERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNS_8ExprListENS_9SourcePosE+0x91): undefined reference to `llvm::GenXIntrinsic::isOverloadedRet(unsigned int)'
/usr/bin/ld: ld-temp.o:(.text._ZN4ispc6Module20AddLLVMIntrinsicDeclERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNS_8ExprListENS_9SourcePosE+0x10f): undefined reference to `llvm::GenXIntrinsic::isOverloadedArg(unsigned int, unsigned int)'
/usr/bin/ld: ld-temp.o:(.text._ZN4ispc6Module20AddLLVMIntrinsicDeclERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNS_8ExprListENS_9SourcePosE+0x2b6): undefined reference to `llvm::GenXIntrinsic::getGenXDeclaration(llvm::Module*, llvm::GenXIntrinsic::ID, llvm::ArrayRef<llvm::Type*>)'
/usr/bin/ld: /tmp/lto-llvm-d034b8.o: in function `ispc::Optimize(llvm::Module*, int)':
ld-temp.o:(.text._ZN4ispc8OptimizeEPN4llvm6ModuleEi+0x51f): undefined reference to `llvm::createISPCSimdCFLoweringPass()'
/usr/bin/ld: ld-temp.o:(.text._ZN4ispc8OptimizeEPN4llvm6ModuleEi+0x4796): undefined reference to `llvm::createGenXSPIRVWriterAdaptorPass(bool, bool)'
/usr/bin/ld: ld-temp.o:(.text._ZN4ispc8OptimizeEPN4llvm6ModuleEi+0x49cf): undefined reference to `llvm::createISPCSimdCFLoweringPass()'
/usr/bin/ld: ld-temp.o:(.text._ZN4ispc8OptimizeEPN4llvm6ModuleEi+0x53b6): undefined reference to `llvm::createGenXSPIRVWriterAdaptorPass(bool, bool)'
/usr/bin/ld: /tmp/lto-llvm-d034b8.o: in function `lRunXeCoalescing(std::map<llvm::Value*, std::map<llvm::Type*, std::vector<PtrUse, std::allocator<PtrUse> >, std::less<llvm::Type*>, std::allocator<std::pair<llvm::Type* const, std::vector<PtrUse, std::allocator<PtrUse> > > > >, std::less<llvm::Value*>, std::allocator<std::pair<llvm::Value* const, std::map<llvm::Type*, std::vector<PtrUse, std::allocator<PtrUse> >, std::less<llvm::Type*>, std::allocator<std::pair<llvm::Type* const, std::vector<PtrUse, std::allocator<PtrUse> > > > > > > >&, std::vector<llvm::Instruction*, std::allocator<llvm::Instruction*> >&)':
ld-temp.o:(.text._ZL16lRunXeCoalescingRSt3mapIPN4llvm5ValueES_IPNS0_4TypeESt6vectorI6PtrUseSaIS6_EESt4lessIS4_ESaISt4pairIKS4_S8_EEES9_IS2_ESaISB_IKS2_SF_EEERS5_IPNS0_11InstructionESaISN_EE+0x794): undefined reference to `llvm::GenXIntrinsic::getGenXDeclaration(llvm::Module*, llvm::GenXIntrinsic::ID, llvm::ArrayRef<llvm::Type*>)'
/usr/bin/ld: /tmp/lto-llvm-d034b8.o: in function `ReplaceLLVMIntrinsics::runOnFunction(llvm::Function&)':
ld-temp.o:(.text._ZN21ReplaceLLVMIntrinsics13runOnFunctionERN4llvm8FunctionE+0x252): undefined reference to `llvm::GenXIntrinsic::getGenXDeclaration(llvm::Module*, llvm::GenXIntrinsic::ID, llvm::ArrayRef<llvm::Type*>)'
/usr/bin/ld: ld-temp.o:(.text._ZN21ReplaceLLVMIntrinsics13runOnFunctionERN4llvm8FunctionE+0x327): undefined reference to `llvm::GenXIntrinsic::getGenXDeclaration(llvm::Module*, llvm::GenXIntrinsic::ID, llvm::ArrayRef<llvm::Type*>)'
/usr/bin/ld: /tmp/lto-llvm-d034b8.o: in function `ImproveMemoryOpsPass::runOnBasicBlock(llvm::BasicBlock&)':
ld-temp.o:(.text._ZN20ImproveMemoryOpsPass15runOnBasicBlockERN4llvm10BasicBlockE+0x5ba0): undefined reference to `llvm::GenXIntrinsic::getGenXDeclaration(llvm::Module*, llvm::GenXIntrinsic::ID, llvm::ArrayRef<llvm::Type*>)'
/usr/bin/ld: ld-temp.o:(.text._ZN20ImproveMemoryOpsPass15runOnBasicBlockERN4llvm10BasicBlockE+0x5c48): undefined reference to `llvm::GenXIntrinsic::getGenXDeclaration(llvm::Module*, llvm::GenXIntrinsic::ID, llvm::ArrayRef<llvm::Type*>)'
/usr/bin/ld: /tmp/lto-llvm-d034b8.o: in function `llvm::filter_iterator_base<llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::GlobalVariable, false, false, void>, false, false>, selectGlobalsToLocalize<llvm::iterator_range<llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::GlobalVariable, false, false, void>, false, false> >, (anonymous namespace)::GlobalsLocalization::AnalyzeGlobals(llvm::CallGraph&)::$_2, int, (anonymous namespace)::GlobalsLocalization::AnalyzeGlobals(llvm::CallGraph&)::$_3>(llvm::iterator_range<llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::GlobalVariable, false, false, void>, false, false> >, int, (anonymous namespace)::GlobalsLocalization::AnalyzeGlobals(llvm::CallGraph&)::$_2, (anonymous namespace)::GlobalsLocalization::AnalyzeGlobals(llvm::CallGraph&)::$_3)::{lambda(llvm::GlobalVariable&)#1}, std::bidirectional_iterator_tag>::findNextValid()':
ld-temp.o:(.text._ZN4llvm20filter_iterator_baseINS_14ilist_iteratorINS_12ilist_detail12node_optionsINS_14GlobalVariableELb0ELb0EvEELb0ELb0EEEZ23selectGlobalsToLocalizeINS_14iterator_rangeIS6_EEZN12_GLOBAL__N_119GlobalsLocalization14AnalyzeGlobalsERNS_9CallGraphEE3$_2iZNSB_14AnalyzeGlobalsESD_E3$_3ESt6vectorINSt15iterator_traitsIDTclsr3stdE5beginclsr3stdE7declvalIRT_EEEEE7pointerESaISM_EESI_T1_T0_T2_EUlRS4_E_St26bidirectional_iterator_tagE13findNextValidEv+0x29): undefined reference to `llvm::GenXIntrinsic::getGenXIntrinsicID(llvm::Function const*)'
```
Maybe there is something wrong with vc-intrinsics itself actually?

**Comment by jbeich** [comment] 2022-03-17 22:29
`igc-1.0.10409` builds fine ([llvm12](http://www.ipv6proxy.net/go.php?u=http://beefy16.nyi.freebsd.org/data/130amd64-default/159bf5bb4c59/logs/intel-graphics-compiler-llvm12-1.0.10409.log), [llvm11](http://www.ipv6proxy.net/go.php?u=http://beefy16.nyi.freebsd.org/data/130amd64-default/159bf5bb4c59/logs/intel-graphics-compiler-llvm11-1.0.10409.log)) on FreeBSD with pre-built vc-intrinsics `v0.1.0`. ispc [used to](http://www.ipv6proxy.net/go.php?u=http://beefy16.nyi.freebsd.org/data/130amd64-default/d79790970038/logs/ispc-1.17.0.log) but FreeBSD support [got regressed](https://github.com/ispc/ispc/issues/2244#issuecomment-1035404143), so no clue if recent versions still do.

**Comment by ArchangeGabriel** [comment] 2022-03-17 22:33
Actually the issue was on our (Arch) side. The issue is that we now enable LTO by default, so `vc-intrinsics` needs to be built with `-ffat-lto-objects` to avoid objects being mangled. I’ve just done that and it works (and I guess ispc will work too, looking at that now). So for me this issue can be closed (or maybe once https://github.com/intel/intel-graphics-compiler/commit/35c947c2631ef4948532eb65c4a62434a580dd3d is available in a release).

**Comment by ArchangeGabriel** [comment] 2022-03-24 12:58
This is now part of the latest release, so should be considered for closing. ;)

**Closed** 2022-03-24 13:01 UTC
