### ISSUE TITLE
Why do some symbol registers have no names?

### ISSUE THREAD

**Issue by onlytheworld** [intel/intel-graphics-compiler#174] opened 2021-04-09 09:37 UTC
When I try to dump all instructions before register allocation, I found that some symbol registers have no names like this
`mov (16)          (0,0)<1>:d  -(0,0)<1;1,0>:d // $204`
I want to know why, and how can I distinguish between different symbol registers?

**Comment by pratikashar** [comment] 2021-06-09 05:05
In Release configuration, IGC may skip propagating virtual variable names to VISA to save memory. Can you try using Debug configuration?

**Comment by paigeale** [comment] 2021-07-30 16:32
@onlytheworld I am closing this issue as it appears this is done by design. If you are still experiencing the above issue with a Debug configuration please reopen and we can address this. Thank you

**Closed by paigeale** 2021-07-30 16:32 UTC
